import Head from 'next/head'
import styles from '../styles/Homepage.module.css'
import React from 'react'
import Select from 'react-select'
import { useState } from 'react'
import Link from 'next/link'

export default function Home() {
  //State
  const [DepartureAirportInput, SetDepartureAirportInput] = useState("")
  const [ArrivalAirportInput, SetArrivalAirportInput] = useState("")
  const [FlightNumberInput, SetFlightNumberInput] = useState("")

  //Dropdown Input Options
  const options = [
    { value: 'KSDF', label: 'KSDF' },
    { value: 'KDTW', label: 'KDTW' },
  ]
  //Dropdown Input Styles
  const customStyles = {
    control: base => ({
      ...base,
      height: 36,
      fontSize: 20,
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>DestiNation-Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/planeLogo.ico"></link>
      </Head>

      <header className={styles.header}>
        <Link href='/about'>
          <h2 className={styles.marginRemove}>About Us</h2>
        </Link>
      </header>

      <main className={styles.main}>
        <div className={styles.leftcontainer}>
          <h1 className={styles.hometitle} >DestiNation</h1>
          <img className={styles.homeimage} src='./Svgs/airplane.png'></img>
        </div>
        <div className={styles.rightcontainer}>
          <form className={styles.formcontainer}>
            <div className={styles.flightSearchCon}>
            <h2 className={styles.formInputHeaders}>Search For Flights</h2>
              <div className={styles.labelinputcontainer}>
                <label className={styles.formlabels}>Departure Airport</label>
                <Select instanceId="DepartureAirportInput" options={options} styles={customStyles} onChange={(event) => SetDepartureAirportInput(event ? event.value : "")} value={options.find(item => item.value === DepartureAirportInput)} />
              </div>
              <div className={styles.labelinputcontainer}>
                <label className={styles.formlabels}>Arrival Airport</label>
                <Select instanceId="ArrivalAirportInput" options={options} styles={customStyles} onChange={(event) => SetArrivalAirportInput(event ? event.value : "")} value={options.find(item => item.value === ArrivalAirportInput)} />
              </div>
              <div className={styles.labelinputcontainer}>
                <label className={styles.formlabels}>Date</label>
                <input type="date" className={styles.forminputs}></input>
              </div>
              <input className={styles.formSubmit} type="submit" value="Find Flights"></input>
            </div>
            <div className={styles.flightNumberSearchCon}>
              <h2 className={styles.formInputHeaders}>Search By Flight Number</h2>
              <div className={styles.labelinputcontainer}>
                <label className={styles.formlabels}>Flight Number</label>
                <input type="input" className={styles.forminputs} onChange={(event) => SetFlightNumberInput(event.target.value)} value={FlightNumberInput} maxLength={6} placeholder="Ex-DL9367"></input>
              </div>
              <div className={styles.labelinputcontainer}>
                <label className={styles.formlabels}>Date</label>
                <input type="date" className={styles.forminputs}></input>
              </div>
              <input className={styles.formSubmit} type="submit" value="Find Flight"></input>
            </div>
          </form>
        </div>
      </main>
    </div>
  )
}
