import Head from 'next/head'
import styles from '../styles/Homepage.module.css'
import React from 'react'
import Link from 'next/link'
import { useRouter } from 'next/router'
export default function Home() {
  
  const router = useRouter()
  
  const HandleFlightNumberForm = async (event) => {
    // Stop the form from submitting and refreshing the page.
    event.preventDefault()
    // Get data from the form.
    const flightNumber = event.target.flightNumber.value 
    const date = event.target.flightDate.value
    // Route to go to.
    const route = `/flight/${flightNumber}/${date}`
    router.push(route) 
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>DestiNation-Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/planeLogo.ico"></link>
      </Head>

      <header className={styles.header}>
        <Link href='/about'>
          <h2 className={styles.marginRemove}>About Us</h2>
        </Link>
      </header>
      <main className={styles.main}>
        <div className={styles.leftcontainer}>
          <h1  className={styles.hometitle} data-testid="homeTitle"  >DestiNation</h1>
          <img className={styles.homeimage} data-testid="homeImage"  alt="Airplane Image" src='./Svgs/airplane.png'></img>
        </div>
        <div className={styles.rightcontainer}>
          <div className={styles.formcontainer}>
            <form className={styles.flightSearchCon}>
            <h2 className={styles.formInputHeaders}>Search Flights</h2>
              <div className={styles.labelinputcontainer}>
                <label className={styles.formlabels}>Arrival Airport</label>
                <input className = {styles.forminputs} placeholder="Ex-SDF" pattern="^[A-Z]{3}$" required></input> 
              </div>
              <div className={styles.labelinputcontainer}>
                <label className={styles.formlabels}>From Local</label>
                <input type="time"required className={styles.forminputs}></input>
              </div>
              <div className={styles.labelinputcontainer}>
                <label className={styles.formlabels}>To Local</label>
                <input type="time"required className={styles.forminputs}></input>
              </div>
              <div className={styles.labelinputcontainer}>
                <label className={styles.formlabels}>Date</label>
                <input type="date" className={styles.forminputs} required ></input>
              </div>
              <input className={styles.formSubmit} type="submit" value="Find Flights"></input>
            </form>
            <form className={styles.flightNumberSearchCon} onSubmit={HandleFlightNumberForm}>
              <h2 className={styles.formInputHeaders}>Search Flight</h2>
              <div className={styles.labelinputcontainer}>
                <label className={styles.formlabels}>Flight Number</label>
                <input type="input" id="flightNumber" name="flightNumber" className={styles.forminputs}  placeholder="Ex-DL9367" pattern="^[A-Z]{2}\d{3,4}$" required></input>
              </div>
              <div className={styles.labelinputcontainer}>
                <label className={styles.formlabels}>Date</label>
                <input type="date" id="flightDate" name="flightDate" className={styles.forminputs} required></input>
              </div>
              <input className={styles.formSubmit} id = "findFlightBtn" type="submit" value="Find Flight"></input>
            </form>
          </div>
        </div>
      </main>
    </div>
  )
}
