name: Build and Test Frontend and Backend 
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  TestFrontend:
    runs-on: ubuntu-latest 
    defaults:
      run:
        working-directory: ./client
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache-dependency-path: '**/package-lock.json' 
    - run: npm install
    - run: cd __tests__
    - run: npm test
  TestBackend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/tests
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3.0.1
      with:
        dotnet-version: 6.0.x
    - run: dotnet test
      
